'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),crypto=require('crypto');
class Range { constructor(s,r,c,rs,cs){this.s=s;this.r=r;this.c=c;this.rs=rs;this.cs=cs;} getValues(){return Array.from({length:this.rs},(_,i)=>Array.from({length:this.cs},(_,j)=>this.s.values[this.r-1+i]?.[this.c-1+j]??''));} setValues(v){v.forEach((row,i)=>row.forEach((x,j)=>{(this.s.values[this.r-1+i]||=[])[this.c-1+j]=x;}));} }
class Sheet { constructor(){this.values=[];} getLastColumn(){return Math.max(0,...this.values.map(r=>r.length));} getLastRow(){return this.values.length;} getRange(r,c,rs,cs){return new Range(this,r,c,rs,cs);} getDataRange(){return new Range(this,1,1,Math.max(1,this.getLastRow()),Math.max(1,this.getLastColumn()));} appendRow(r){this.values.push(r);} setFrozenRows(){} }
class SS { constructor(){this.s={};} getSheetByName(n){return this.s[n]||null;} insertSheet(n){return this.s[n]=new Sheet();} }
const ss=new SS(),ctx={console,JSON,Number,String,Object,Array,Date,Math,RegExp,Utilities:{getUuid:()=>crypto.randomUUID(),formatDate:(d,t,f)=>f==='yyyy-MM-dd'?'2026-07-24':'2026-07-24T12:00:00+09:00',base64Encode:b=>Buffer.from(b).toString('base64'),computeDigest:(a,s)=>crypto.createHash('sha256').update(s).digest(),DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'}},PropertiesService:{getScriptProperties:()=>({getProperty:k=>k==='HEALTH_SPREADSHEET_ID'?'sheet':''})},SpreadsheetApp:{openById:()=>ss},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})} };vm.createContext(ctx);['HealthSetup.js','HealthSecurity.js','HealthRuleService.js','HealthDataService.js','HealthDailyAuditService.js','HealthIdempotencyRecovery.js'].forEach(f=>vm.runInContext(fs.readFileSync('gas-health/'+f,'utf8'),ctx));ctx.setupHealthSchema_();
const id='11111111-1111-4111-8111-111111111111',base={operation:'health.daily.recordSlot',homeId:'h',actorUserId:'son',targetUserId:'son',localDate:'2026-07-24',slot:'morning',payload:{morningStaple:'none',morningProteinSource:'none',morningWater:false,morningMedication:false,morningCondition:false},clientRequestId:id};
const first=ctx.executeIdempotentWrite_(base),replayed=ctx.executeIdempotentWrite_(base);
assert(first.data.slots.morning.recordedAt,'recordedAt missing after partial morning save');
assert(first.data.ruleCodes.includes('morning_fuel_missing'),'content evaluation disappeared after partial morning save');
assert(!first.data.ruleCodes.includes('morning_not_recorded'),'partial morning save remained record-incomplete');
assert.equal(replayed.data.slots.morning.recordedAt,first.data.slots.morning.recordedAt,'idempotent replay changed recordedAt');
assert.equal(ss.s.Health_Daily.getLastRow(),2);assert.equal(ss.s.Health_Request_Log.getLastRow(),2);assert.throws(()=>ctx.executeIdempotentWrite_({...base,payload:{morningStaple:'normal',morningProteinSource:'none',morningWater:false,morningMedication:false,morningCondition:false}}),e=>e.code==='IDEMPOTENCY_CONFLICT');
const id2='22222222-2222-4222-8222-222222222222',failed={...base,clientRequestId:id2};const original=ctx.appendRequestLog_;ctx.appendRequestLog_=()=>{throw new Error('log failure');};assert.throws(()=>ctx.executeIdempotentWrite_(failed));ctx.appendRequestLog_=original;ctx.executeIdempotentWrite_(failed);assert.equal(ss.s.Health_Daily.getLastRow(),2);assert.equal(ss.s.Health_Request_Log.getLastRow(),3);
const weightId='33333333-3333-4333-8333-333333333333',weight={operation:'health.weight.record',homeId:'h',actorUserId:'son',targetUserId:'son',measuredDate:'2026-07-24',weightKg:55,clientRequestId:weightId};ctx.appendRequestLog_=()=>{throw new Error('log failure');};assert.throws(()=>ctx.executeIdempotentWrite_(weight));ctx.appendRequestLog_=original;ctx.executeIdempotentWrite_(weight);assert.equal(ss.s.Health_Weight.getLastRow(),2);assert.equal(ctx.weightList_({homeId:'h',targetUserId:'son',limit:8}).items.length,1);assert.throws(()=>ctx.weightList_({homeId:'h',targetUserId:'son',limit:21}),e=>e.code==='INVALID_INPUT');
console.log('PASS health schema, slots, idempotency, log recovery, weights');
