'use strict';
const assert=require('node:assert/strict');
const inbox=require('../features/kaz-os/inbox'),{health}=require('../features/kaz-os/personal');
const {inlineDecisionFixture,decisionFixture}=require('./fixtures/kaz-decision-view');
const now=Date.parse('2026-09-14T09:30:00+09:00'),cases=[];
const summary=(d,id)=>inbox.inlineSummary(d,d.inbox_items.find(i=>i.id===id),now,health);
const answer=(d,id,decision,extra={})=>inbox.inlineAnswer(d,id,{decision,...extra},now,health);
function test(name,fn){fn();cases.push(name);}
function secretaryFixture(kind='today_focus'){
  const source={status:'ok',complete:true,fetched_at:'2026-09-14T09:29:00+09:00',valid_until:'2026-09-14T09:45:00+09:00',scope:'test read-only'},refs={projects:'project-observation',work_items:'work-observation',calendar:'calendar-observation'},question='今日の先頭候補にする？',revision='question-sha256:'+'a'.repeat(64);
  const item={id:'decision-real-1',kind,contract:'secretary-question-0.1',owner:'kaz',decision_requested:true,decision_status:'pending',title:'PoCのAcceptance・次運用方針を決める',question,reason:'REVIEW中Projectの判断を確認',impact:'今日の候補を決める',estimate_min:null,affects_today:true,urgent_today:true,decision_date:'2026-09-14',due_at:'2026-09-15T00:00:00+09:00',project_id:'project-1',entity_ref:'WI-10',source_label:'Notion Work Items',entity_revision:'2026-09-14T09:20:00+09:00',question_revision:revision,source_revision_references:refs,answer_contract:{inbox_item_id:'decision-real-1',question_revision:revision,question,choices:[{value:'today',label:'今日',effect:'Today candidate'},{value:'this_week',label:'今週',effect:'今週候補'},{value:'later',label:'あとで',effect:'後日候補'}]},selection_mode:null,selection_options:null,recommended_option:'today',recommendation_basis:['Project REVIEW']};
  return{schema_version:'kaz-secretary-inbox-0.1',origin:'real_operational_sources',mode:'local_controlled_proposal',fixture_only:false,as_of:'2026-09-14T09:30:00+09:00',sources:{inbox:{...source,source_revision:'question-set'},projects:{...source,source_revision:refs.projects},tasks:{...source,source_revision:refs.work_items},calendar:{...source,source_revision:refs.calendar},resolution:{...source,source_revision:refs.calendar}},projects:[{id:'project-1',title:'Quality Quest',status:'REVIEW',source_revision:'2026-09-14T09:15:00+09:00'}],work_items:[{id:'WI-10',title:item.title,state:'READY',project_id:'project-1',revision:item.entity_revision,source_revision:item.entity_revision,estimate_min:null,next_actor:'kaz',blocker:'',action_instruction:item.title,dependencies:[]}],calendar_events:[],inbox_items:[item],decision_priority_evidence:{},writes:{notion:0,calendar:0,context:0}};
}
test('100 requests and five TODAY selected without a new triage score',()=>{const d=inlineDecisionFixture(),v=inbox.derive(d,now,health);assert.equal(v.total,100);assert.equal(v.today.length,5);assert.equal(d.work_items.length,100);assert.equal(v.today[0].id,'di-081');});
test('classification shows real fixture event subject and three explicit answers',()=>{const d=inlineDecisionFixture(),s=summary(d,'di-081');assert.equal(s.title,'次男 ハンドボール');assert.deepEqual(s.choices.map(c=>c.label),['はい','いいえ','わからん']);});
test('classification yes/no/unknown never infers actor or adopts constraint',()=>{for(const [choice,impact] of [['hard_constraint','hard_constraint'],['none','none'],['unknown','unknown']]){const d=inlineDecisionFixture(),before=JSON.stringify(d),p=answer(d,'di-081',choice);assert.equal(p.classification_proposal.impact_on_kaz,impact);assert.equal(p.classification_proposal.actor,'unknown');assert.equal(p.classification_proposal.confirmation,null);assert.equal(p.adopted,false);assert.equal(JSON.stringify(d),before);}});
test('Idea inline answers preserve literal response without invented reason',()=>{for(const choice of ['promote','incubate','reject']){const d=inlineDecisionFixture(),p=answer(d,'di-031',choice);assert.equal(p.status,'proposal');assert.equal(p.reason,`${p.question} → ${p.answer_label}（追加理由なし）`);assert.equal(p.persisted,false);}});
test('Context actions are exactly candidate/reject; no promotion',()=>{const d=inlineDecisionFixture();assert.deepEqual(summary(d,'di-061').choices.map(c=>c.label),['候補にする','不要']);answer(d,'di-061','review');assert.equal(d.context_candidates[0].curated,false);});
test('Blocker choices require item and revision-bound decision contract',()=>{const d=inlineDecisionFixture();assert.deepEqual(summary(d,'di-091').choices.map(c=>c.label),['進める','まだ待つ']);delete d.inbox_items[90].answer_contract;assert.throws(()=>answer(d,'di-091','unblock'));});
test('Human Review summary has six bound Evidence points and known metrics',()=>{const s=summary(inlineDecisionFixture(),'di-001');assert.equal(s.issues.length,0);assert.equal(s.checks.length,6);assert(s.metrics.includes('Tests 128 / 128 PASS'));assert(s.metrics.includes('変更 2 files'));assert(s.metrics.includes('Regression 0'));});
test('missing metrics remain unknown instead of zero',()=>{const d=inlineDecisionFixture(),p=d.review_packets[d.inbox_items[0].entity_ref];delete p.regression_summary;delete p.test_summary;p.changed_files=null;assert.deepEqual(summary(d,'di-001').metrics,['Codex completed','Tests 未取得','変更files 未取得','Regression 未取得']);});
test('Human Review cannot automatically acknowledge summaries',()=>assert.throws(()=>answer(inlineDecisionFixture(),'di-001','ACCEPTED')));
test('explicit summary confirmation still calls existing proposal contract',()=>{const d=inlineDecisionFixture(),before=JSON.stringify(d),p=answer(d,'di-001','ACCEPTED',{confirmed_summary:true});assert.equal(p.checked_evidence.length,6);assert.equal(p.continuation,'lifecycle.human_review');assert.equal(p.summary_confirmed,true);assert.equal(JSON.stringify(d),before);});
test('rework requires a user reason and keeps it verbatim',()=>{const d=inlineDecisionFixture();assert.throws(()=>answer(d,'di-001','REWORK_REQUIRED',{confirmed_summary:true}));const p=answer(d,'di-001','REWORK_REQUIRED',{confirmed_summary:true,reason:'再試行時のフォーム状態を確認したい'});assert.equal(p.reason,'再試行時のフォーム状態を確認したい');});
test('Acceptance summary has each criterion; Human Review remains separate',()=>{const d=inlineDecisionFixture(),s=summary(d,'di-021');assert.equal(s.checks.length,3);const p=answer(d,'di-021','ACCEPTED',{confirmed_summary:true});assert.equal(p.checked_evidence.length,3);assert.equal(p.continuation,'lifecycle.acceptance');assert.equal(d.work_items.find(w=>w.id===p.entity_ref).state,'ACCEPTANCE');});
test('unaccepted Human Review prevents Acceptance inline',()=>{const d=inlineDecisionFixture();d.review_packets[d.inbox_items[20].entity_ref].human_review_status='pending';assert.throws(()=>answer(d,'di-021','ACCEPTED',{confirmed_summary:true}));});
test('mandatory detail and unapproved summary policy cannot be bypassed',()=>{for(const mode of ['requires_detail','policy','conflict']){const d=inlineDecisionFixture(),i=d.inbox_items[0];if(mode==='requires_detail')i.requires_detail=true;else if(mode==='policy')i.review_policy.mode='detail_required';else i.kind='conflict_resolution';assert(summary(d,'di-001').issues.length);assert.throws(()=>answer(d,'di-001','ACCEPTED',{confirmed_summary:true}));}});
test('summary missing stale duplicate or wrong Evidence hash blocks inline',()=>{for(const mode of ['missing','stale','duplicate','hash','ref']){const d=inlineDecisionFixture(),p=d.review_packets[d.inbox_items[0].entity_ref];if(mode==='missing')p.evidence_summaries.pop();if(mode==='stale')p.evidence_summaries[0].source_revision='old';if(mode==='duplicate')p.evidence_summaries.push(p.evidence_summaries[0]);if(mode==='hash')p.evidence_summaries[0].sha256='f'.repeat(64);if(mode==='ref')p.evidence_summaries[0].ref='wrong';assert.throws(()=>answer(d,'di-001','ACCEPTED',{confirmed_summary:true}));}});
test('regression failures require detail instead of quick approval',()=>{const d=inlineDecisionFixture();d.review_packets[d.inbox_items[0].entity_ref].regression_summary.failures=1;assert.throws(()=>answer(d,'di-001','ACCEPTED',{confirmed_summary:true}));});
test('unbound metric is not displayed as PASS',()=>{const d=inlineDecisionFixture();d.review_packets[d.inbox_items[0].entity_ref].test_summary.source_revision='old';assert(summary(d,'di-001').metrics.includes('Tests 未取得'));});
test('legacy packet uses detail instead of fabricating a summary',()=>assert(summary(decisionFixture(),'di-001').issues.length>0));
test('stale source blocks inline and hides normal Evidence metrics',()=>{const d=inlineDecisionFixture();d.sources.runs.status='stale';assert.throws(()=>answer(d,'di-001','ACCEPTED',{confirmed_summary:true}));assert.equal(summary(d,'di-001').metrics.length,1);assert(summary(d,'di-001').metrics[0].includes('再確認'));});
test('Decision Request and Work Item remain separate objects and ids',()=>{const d=inlineDecisionFixture(),p=answer(d,'di-031','promote');assert.notEqual(p.inbox_item_id,p.entity_ref);assert.equal(p.authority,'untrusted_ui_draft');assert.equal(d.inbox_items.find(i=>i.id===p.inbox_item_id).decision_status,'pending');});
test('real secretary question keeps revision bindings and creates answer input only',()=>{const d=secretaryFixture(),s=summary(d,'decision-real-1'),p=answer(d,'decision-real-1','today');assert.deepEqual(s.choices.map(c=>c.label),['今日','今週','あとで']);assert.equal(p.status,'answer_pending');assert.equal(p.mode,'local_controlled_proposal');assert.equal(p.selected_option,'today');assert.equal(p.question_revision,d.inbox_items[0].question_revision);assert.deepEqual(p.source_revision_references,d.inbox_items[0].source_revision_references);assert.equal(p.persisted,false);assert.equal(p.reason,null);});
test('real secretary question blocks changed Work Item or source revision',()=>{for(const part of ['entity','source']){const d=secretaryFixture();if(part==='entity')d.work_items[0].source_revision='changed';else d.sources.tasks.source_revision='changed';assert.throws(()=>answer(d,'decision-real-1','today'));}});
console.log(`kaz-inbox-inline: ${cases.length}/${cases.length} PASS`);
