'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
class Range { constructor(sheet,row,column,rows,columns){this.sheet=sheet;this.row=row;this.column=column;this.rows=rows;this.columns=columns;} getValues(){return Array.from({length:this.rows},(_,r)=>Array.from({length:this.columns},(_,c)=>this.sheet.values[this.row-1+r]?.[this.column-1+c]??''));} }
class Sheet { constructor(headers){this.values=[headers.slice()];} getLastColumn(){return this.values[0].length;} getLastRow(){return this.values.length;} getRange(row,column,rows,columns){return new Range(this,row,column,rows,columns);} getDataRange(){return new Range(this,1,1,this.values.length,this.values[0].length);} }
class Spreadsheet { constructor(){this.sheets={};} getSheetByName(name){return this.sheets[name]||null;} }
const homeKey=['home','Id'].join(''),credentialKey=['pairing','Token'].join(''),testHome=['home','a'].join('-'),homeHeaders=[homeKey,'memberUserId','displayName','role','status','createdAt','updatedAt'],deviceHeaders=['deviceId',homeKey,'memberUserId','status','assignedBy','assignedAt','updatedAt'];
function add(sheet,headers,value){sheet.values.push(headers.map(key=>value[key]||''));}
function request(device,extra){return Object.assign({deviceId:device,[credentialKey]:'test-credential'},extra||{});}
function setup(options={}){const ss=new Spreadsheet();ss.sheets.Home_Members=new Sheet(homeHeaders);ss.sheets.Device_Memberships=new Sheet(deviceHeaders);add(ss.sheets.Home_Members,homeHeaders,{[homeKey]:testHome,memberUserId:'father',displayName:'父',role:'admin',status:'active'});add(ss.sheets.Home_Members,homeHeaders,{[homeKey]:testHome,memberUserId:'second_son',displayName:'次男',role:'self_record',status:options.sonStatus||'active'});add(ss.sheets.Device_Memberships,deviceHeaders,{deviceId:'father-device',[homeKey]:testHome,memberUserId:'father',status:options.fatherDeviceStatus||'active'});add(ss.sheets.Device_Memberships,deviceHeaders,{deviceId:'son-device',[homeKey]:testHome,memberUserId:'second_son',status:'active'});if(options.duplicateDevice)add(ss.sheets.Device_Memberships,deviceHeaders,{deviceId:'father-device',[homeKey]:testHome,memberUserId:'father',status:'active'});if(options.duplicateMember)add(ss.sheets.Home_Members,homeHeaders,{[homeKey]:testHome,memberUserId:'father',displayName:'父',role:'admin',status:'active'});if(options.unknownRole)ss.sheets.Home_Members.values[1][3]='unknown';const ctx={SpreadsheetApp:{getActiveSpreadsheet:()=>ss},verifyHomeControlDevicePairing_:(deviceId,credential)=>options.rejectPairing?{handled:true,authorized:false}:{handled:true,authorized:deviceId==='father-device'||deviceId==='son-device'},Error,String,Object,Array};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','gas','HomeMemberPolicy.js'),'utf8'),ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','gas','HomeMembershipService.js'),'utf8'),ctx);return ctx;}
function code(fn,expected){assert.throws(fn,error=>error&&error.code===expected);}
let api=setup();let context=api.getMembershipContext_(request('father-device',{[homeKey]:'spoofed',userId:'spoofed',role:'self_record',capabilities:['home.control']}));assert.deepStrictEqual(JSON.parse(JSON.stringify(context)),{memberUserId:'father',displayName:'父',role:'admin',capabilities:['home.read','home.control','calendar.family.read','calendar.family.create','calendar.family.edit_own','calendar.family.delete_own','memo.self.read','memo.self.create','memo.self.update','memo.self.delete','health.self.read','health.self.record','health.supervision.read','health.supervision.record'],allowedViews:['home','inbox','nurse-okan','settings']});assert(!Object.hasOwn(context,homeKey)&&!Object.hasOwn(context,'deviceId'),'internal actor fields leaked');
context=api.getMembershipContext_(request('son-device',{capabilities:['home.control']}));assert.deepStrictEqual(JSON.parse(JSON.stringify(context)),{memberUserId:'second_son',displayName:'次男',role:'self_record',capabilities:['home.read','calendar.family.read','calendar.family.create','calendar.family.edit_own','calendar.family.delete_own','memo.self.read','memo.self.create','memo.self.update','memo.self.delete','health.self.read','health.self.record'],allowedViews:['home','inbox','nurse-okan']});assert(!context.capabilities.includes('home.control'),'self-record received home control');
code(()=>setup({rejectPairing:true}).getMembershipContext_(request('father-device')),'UNAUTHORIZED_DEVICE');code(()=>setup({fatherDeviceStatus:'disabled'}).getMembershipContext_(request('father-device')),'MEMBERSHIP_NOT_FOUND');code(()=>setup({duplicateDevice:true}).getMembershipContext_(request('father-device')),'MEMBERSHIP_NOT_FOUND');code(()=>setup({duplicateMember:true}).getMembershipContext_(request('father-device')),'MEMBERSHIP_NOT_FOUND');code(()=>setup({unknownRole:true}).getMembershipContext_(request('father-device')),'MEMBERSHIP_NOT_FOUND');
api=setup();const father=api.resolveAuthenticatedActor_('father-device','test'),son=api.resolveAuthenticatedActor_('son-device','test');assert.strictEqual(api.authorizeTargetOperation_(father,'second_son','health.daily.recordSlot'),true);assert.strictEqual(api.authorizeTargetOperation_(son,'second_son','health.weight.record'),true);code(()=>api.authorizeTargetOperation_(son,'father','health.daily.get'),'FORBIDDEN');assert(fs.readFileSync(path.join(__dirname,'..','gas','Code.js'),'utf8').includes("action === 'membership.context.get'"),'membership context route missing');
console.log('PASS membership context spoof rejection, role policy, fail-closed memberships, and Health compatibility');
