'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
class Range{constructor(s,r,c,rs,cs){this.s=s;this.r=r;this.c=c;this.rs=rs;this.cs=cs;}getValues(){return Array.from({length:this.rs},(_,i)=>Array.from({length:this.cs},(_,j)=>this.s.v[this.r-1+i]?.[this.c-1+j]??''));}setValues(v){v.forEach((row,i)=>row.forEach((x,j)=>{(this.s.v[this.r-1+i]||=[])[this.c-1+j]=x;}));}setValue(x){(this.s.v[this.r-1]||=[])[this.c-1]=x;}setNumberFormat(){}}
class Sheet{constructor(v){this.v=v.map(r=>r.slice());}getLastColumn(){return this.v[0].length;}getLastRow(){return this.v.length;}getRange(r,c,rs=1,cs=1){return new Range(this,r,c,rs,cs);}appendRow(r){this.v.push(r);}deleteRow(r){this.v.splice(r-1,1);}setFrozenRows(){}}
const headers=['id','memo','title','ownerUserId','createdByUserId','userId','userDisplayName','deviceId','status'];
const sheet=new Sheet([headers,['father-id','father memo','F','father','father','father','Father','father-device','inbox'],['son-id','son memo','S','second_son','second_son','second_son','Son','son-device','inbox']]);
const ctx={SpreadsheetApp:{getActiveSpreadsheet:()=>({getSheetByName:n=>n==='01_Inbox'?sheet:null})},Utilities:{getUuid:()=> 'new-id',formatDate:()=> '2026-07-26T00:00:00+09:00'},console,JSON,Math,Number,String,Object,Array,Date,RegExp,Error};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','gas','MemoOwnershipService.js'),'utf8'),ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','gas','HomeMemberPolicy.js'),'utf8'),ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','gas','Code.js'),'utf8'),ctx);ctx.json_=x=>x;
ctx.resolveAuthenticatedActor_=(device,token)=>{if(token!=='credential')throw Object.assign(new Error('UNAUTHORIZED_DEVICE'),{code:'UNAUTHORIZED_DEVICE'});return device==='father-device'?{homeId:'h',memberUserId:'father',deviceId:device,role:'admin'}:device==='son-device'?{homeId:'h',memberUserId:'second_son',deviceId:device,role:'self_record'}:(()=>{throw Object.assign(new Error('UNAUTHORIZED_DEVICE'),{code:'UNAUTHORIZED_DEVICE'});})();};ctx.authorizeCapability_=()=>true;ctx.getHomeMember_=(h,id)=>({memberUserId:id,displayName:id==='father'?'Father':'Son',status:'active'});ctx.homeMembershipError_=code=>Object.assign(new Error(code),{code});
function body(device='father-device',extra={}){return Object.assign({deviceId:device,pairingToken:'credential'},extra);}function code(fn,c){assert.throws(fn,e=>e&&e.code===c);}
assert.equal(ctx.getOwnedMemoItem_('father-id',ctx.resolveMemoActor_((body()),'memo.self.read')).item.ownerUserId,'father');code(()=>ctx.getOwnedMemoItem_('father-id',ctx.resolveMemoActor_(body('son-device'),'memo.self.read')),'FORBIDDEN');code(()=>ctx.resolveMemoActor_(body('father-device',{pairingToken:''}),'memo.self.read'),'UNAUTHORIZED_DEVICE');
assert.deepStrictEqual(JSON.parse(JSON.stringify(ctx.listInboxItems_(ctx.resolveMemoActor_(body('son-device'),'memo.self.read')).map(x=>x.id))),['son-id']);
sheet.v[2][3]='';code(()=>ctx.getOwnedMemoItem_('son-id',ctx.resolveMemoActor_(body('son-device'),'memo.self.read')),'MEMO_OWNERSHIP_INCONSISTENT');sheet.v[2][3]='second_son';
code(()=>ctx.assertMemoIdentityFieldsAbsent_({userId:'spoof'}),'FORBIDDEN');code(()=>ctx.assertMemoIdentityFieldsAbsent_({ownerUserId:'father'}),'FORBIDDEN');
ctx.assertMemoIdentityFieldsAbsent_({deviceId:'father-device',pairingToken:'credential'});
const updateIndex=headers.reduce((result,header,index)=>{result[header]=index;return result;},{});
ctx.getInboxSheet_=()=>sheet;ctx.getHeaderIndex_=()=>updateIndex;ctx.findRowNumberById_=()=>2;ctx.getOwnedMemoItem_=(id,actor)=>({sheet,rowNumber:2,index:updateIndex,item:{id:'father-id',memo:'father memo',title:'F',ownerUserId:actor.memberUserId,createdByUserId:actor.memberUserId,status:'inbox',type:'note'}});ctx.normalizeValueForSheet_=(field,value)=>value;ctx.validateAnalyzedItem_=item=>item;ctx.setSheetValueForField_=(target,row,column,field,value)=>{target.v[row-1][column-1]=value;};ctx.hasCalendarRelevantChanges_=()=>false;ctx.sanitizeItemForClient_=item=>item;ctx.nowTokyoString_=()=> '2026-07-27 12:00:00';ctx.getCalendarSuffixForMember_=()=>'';
const updateResult=ctx.updateItem_(body('father-device',{id:'father-id',status:'Done'}));assert(updateResult.success===true&&updateResult.item.status==='Done','authenticated owner update failed');
ctx.getOwnedMemoItem_=()=>{throw ctx.homeMembershipError_('FORBIDDEN');};assert.throws(()=>ctx.updateItem_(body('father-device',{id:'other-id',status:'Done'})),e=>e&&e.code==='FORBIDDEN','cross-owner update was not rejected');
let saved;ctx.appendNewItem_=item=>{saved=item;return item;};ctx.analyzeMemoWithAI_=()=>({title:'x',category:'',priority:'Normal',tags:[],needsFollowup:false});const created=ctx.createItemWithAI_(body('father-device',{memo:'private',userId:'second_son',ownerUserId:'second_son',createdByUserId:'second_son',role:'self_record'}));assert.equal(saved.ownerUserId,'father');assert.equal(saved.createdByUserId,'father');assert.equal(saved.userId,'father');assert(!JSON.stringify(created).includes('credential'),'pairing credential leaked');
const source=fs.readFileSync(path.join(__dirname,'..','gas','Code.js'),'utf8'),app=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8'),docs=fs.readFileSync(path.join(__dirname,'..','docs','paluru-multi-user-design.md'),'utf8');assert(!source.includes("if (action === 'list') {\n      return json_"),'GET list remains public');['createWithAI','list','update','delete','answerFollowup','notificationCandidates','syncCalendar','updateCalendar'].forEach(name=>assert(source.includes("action === '"+name+"'"),'route missing '+name));assert(app.includes('buildMemoCredentialPayload("list")')&&app.includes('buildMemoCredentialPayload("delete")'),'PWA credential routing missing');assert(docs.includes('Phase 0B2 Agent Chat boundary'),'Agent Chat boundary undocumented');
console.log('PASS memo owner auth, spoof rejection, cross-owner denial, migration fail-closed, internal boundary, and credential non-leak');
