'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm');
let domReady;const ctx={console,JSON,Error,Object,String,Array,Number,Promise,module:{exports:{}},exports:{},crypto:{randomUUID:()=> '11111111-1111-4111-8111-111111111111'},document:{addEventListener:(name,fn)=>{if(name==='DOMContentLoaded')domReady=fn;}},localStorage:{getItem:()=>''},navigator:{onLine:true}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('features/nurse-okan/nurse-okan.js','utf8'),ctx);const api=ctx.module.exports;assert(api&&domReady,'CommonJS export or delayed initializer missing');
const payload=api.buildGatewayPayload_('health.daily.recordSlot',{deviceId:'device-1'},'pairing-1','second_son',{localDate:'2026-07-24',slot:'morning',payload:{morningStaple:'normal'}});assert.deepStrictEqual(JSON.parse(JSON.stringify(payload)),{action:'health.daily.recordSlot',deviceId:'device-1',pairingToken:'pairing-1',targetMemberUserId:'second_son',localDate:'2026-07-24',slot:'morning',payload:{morningStaple:'normal'}});['homeId','actorUserId','actorRole','recordedBy','serviceToken'].forEach(k=>assert(!Object.hasOwn(payload,k)));assert(!/growth/i.test(fs.readFileSync('features/nurse-okan/nurse-okan.js','utf8')),'Growth API reference found');
async function run(){let calls=0,status=[],serverDaily=null,settled=0;let release;const pending=new Promise(r=>release=r);const flow=api.createNurseOkanSaveFlow_({call:async()=>{calls++;return pending;},onSaving:()=>status.push('saving'),onSuccess:async(a,d)=>{serverDaily=d;},onSaved:()=>status.push('saved'),onFailure:e=>status.push(e.code==='OFFLINE'?'offline':'error'),onSettled:()=>settled++});const first=flow.save('health.daily.recordSlot',{x:1}),second=flow.save('health.daily.recordSlot',{x:1});assert.equal(calls,1);assert(!status.includes('saved'));assert(flow.isSaving());assert.equal((await second).skipped,true);release({server:'daily'});assert.equal((await first).data.server,'daily');assert.equal(serverDaily.server,'daily');assert.deepStrictEqual(status,['saving','saved']);assert.equal(settled,1);assert(!flow.isSaving());
let offlineCalls=0,offlineStatus=[];const offline=api.createNurseOkanSaveFlow_({call:async()=>{offlineCalls++;const e=new Error('OFFLINE');e.code='OFFLINE';throw e;},onSaving:()=>offlineStatus.push('saving'),onSuccess:async()=>{},onSaved:()=>offlineStatus.push('saved'),onFailure:e=>offlineStatus.push(e.code==='OFFLINE'?'offline':'error'),onSettled:()=>{}});const input={morningStaple:'normal'};const offlineResult=await offline.save('health.daily.recordSlot',input);assert.equal(offlineCalls,1);assert.equal(offlineResult.saved,false);assert.deepStrictEqual(input,{morningStaple:'normal'});assert.deepStrictEqual(offlineStatus,['saving','offline']);assert(!offline.isSaving());
let failed=0;const failure=api.createNurseOkanSaveFlow_({call:async()=>{failed++;throw new Error('gateway');},onSaving:()=>{},onSuccess:async()=>{},onSaved:()=>{throw new Error('must not save');},onFailure:()=>{},onSettled:()=>{}});assert.equal((await failure.save('health.daily.recordSlot',{kept:true})).saved,false);assert.equal((await failure.save('health.daily.recordSlot',{kept:true})).saved,false);assert.equal(failed,2);assert(!failure.isSaving());
let record=0,list=0,weightState;const weight=api.createNurseOkanSaveFlow_({call:async action=>{if(action==='health.weight.record'){record++;return {weightKg:55};}if(action==='health.weight.list'){list++;return {items:[{weightKg:55}]};}},onSaving:()=>{},onSuccess:async(action,data)=>{if(action==='health.weight.record'){list++;weightState={items:[{weightKg:55}]};}},onSaved:()=>{},onFailure:()=>{},onSettled:()=>{}});await weight.save('health.weight.record',{weightKg:55});assert.equal(record,1);assert.equal(list,1);assert.deepStrictEqual(weightState,{items:[{weightKg:55}]});
console.log('PASS nurse UI double-save, offline, failure retry, weight refresh, payload boundary, delayed initialization');}
run().catch(e=>{console.error(e);process.exitCode=1;});
