'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm');
let domReady;const ctx={console,JSON,Error,Object,String,Array,Number,Promise,module:{exports:{}},exports:{},crypto:{randomUUID:()=> '11111111-1111-4111-8111-111111111111'},document:{addEventListener:(name,fn)=>{if(name==='DOMContentLoaded')domReady=fn;}},localStorage:{getItem:()=>''},navigator:{onLine:true}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('features/nurse-okan/nurse-okan.js','utf8'),ctx);const api=ctx.module.exports;assert(api&&domReady,'CommonJS export or delayed initializer missing');
const nurseUiSource=fs.readFileSync('features/nurse-okan/nurse-okan.js','utf8');assert(nurseUiSource.includes('assets/character/okan/expressions/okan_bust_gentle.png'),'Nurse Okan character image path missing');assert(nurseUiSource.includes('alt="やさしく見守るナースおかん"'),'Nurse Okan character alt missing');assert(!nurseUiSource.includes('<details id="nursePanel">'),'legacy Nurse Okan details remains');assert(nurseUiSource.includes('class="nurse-okan-content"'),'always-open Nurse Okan content missing');
function fakeControl(targetView){const listeners={};return {dataset:targetView?{targetView}: {},hidden:false,classList:{values:new Set(),toggle(name,enabled){enabled?this.values.add(name):this.values.delete(name);},contains(name){return this.values.has(name);}},setAttribute(name,value){this[name]=value;},addEventListener(name,fn){listeners[name]=fn;},fire(name,event={}){listeners[name](event);}};}
const toggle=fakeControl(),drawer=fakeControl(),overlay=fakeControl(),closeButton=fakeControl(),keyTarget=fakeControl(),nurseMenu=fakeControl('nurse-okan');let requestedView='';const drawerController=api.createDrawerController_({toggle,drawer,overlay,closeButton,menuItems:[nurseMenu],keyTarget,onNavigate:viewName=>{requestedView=viewName;}});toggle.fire('click');assert(drawerController.isOpen()&&drawer.classList.contains('is-open')&&overlay.hidden===false&&toggle['aria-expanded']==='true','drawer open state missing');overlay.fire('click');assert(!drawerController.isOpen()&&overlay.hidden===true,'drawer outside close missing');toggle.fire('click');keyTarget.fire('keydown',{key:'Escape'});assert(!drawerController.isOpen(),'drawer Escape close missing');toggle.fire('click');nurseMenu.fire('click');assert(!drawerController.isOpen()&&requestedView==='nurse-okan','Nurse Okan drawer navigation missing');
const payload=api.buildHealthRequest_('health.daily.recordSlot','second_son',{localDate:'2026-07-24',slot:'morning',payload:{morningStaple:'normal'}});assert.deepStrictEqual(JSON.parse(JSON.stringify(payload)),{action:'health.daily.recordSlot',targetMemberUserId:'second_son',localDate:'2026-07-24',slot:'morning',payload:{morningStaple:'normal'}});['deviceId','pairingToken','homeId','actorUserId','actorRole','recordedBy','serviceToken'].forEach(k=>assert(!Object.hasOwn(payload,k)));assert(!/growth/i.test(fs.readFileSync('features/nurse-okan/nurse-okan.js','utf8')),'Growth API reference found');
async function run(){let calls=0,status=[],serverDaily=null,settled=0;let release;const pending=new Promise(r=>release=r);const flow=api.createNurseOkanSaveFlow_({call:async()=>{calls++;return pending;},onSaving:()=>status.push('saving'),onSuccess:async(a,d)=>{serverDaily=d;},onSaved:()=>status.push('saved'),onFailure:e=>status.push(e.code==='OFFLINE'?'offline':'error'),onSettled:()=>settled++});const first=flow.save('health.daily.recordSlot',{x:1}),second=flow.save('health.daily.recordSlot',{x:1});assert.equal(calls,1);assert(!status.includes('saved'));assert(flow.isSaving());assert.equal((await second).skipped,true);release({server:'daily'});assert.equal((await first).data.server,'daily');assert.equal(serverDaily.server,'daily');assert.deepStrictEqual(status,['saving','saved']);assert.equal(settled,1);assert(!flow.isSaving());
let offlineCalls=0,offlineStatus=[];const offline=api.createNurseOkanSaveFlow_({call:async()=>{offlineCalls++;const e=new Error('OFFLINE');e.code='OFFLINE';throw e;},onSaving:()=>offlineStatus.push('saving'),onSuccess:async()=>{},onSaved:()=>offlineStatus.push('saved'),onFailure:e=>offlineStatus.push(e.code==='OFFLINE'?'offline':'error'),onSettled:()=>{}});const input={morningStaple:'normal'};const offlineResult=await offline.save('health.daily.recordSlot',input);assert.equal(offlineCalls,1);assert.equal(offlineResult.saved,false);assert.deepStrictEqual(input,{morningStaple:'normal'});assert.deepStrictEqual(offlineStatus,['saving','offline']);assert(!offline.isSaving());
let failed=0;const failure=api.createNurseOkanSaveFlow_({call:async()=>{failed++;throw new Error('gateway');},onSaving:()=>{},onSuccess:async()=>{},onSaved:()=>{throw new Error('must not save');},onFailure:()=>{},onSettled:()=>{}});assert.equal((await failure.save('health.daily.recordSlot',{kept:true})).saved,false);assert.equal((await failure.save('health.daily.recordSlot',{kept:true})).saved,false);assert.equal(failed,2);assert(!failure.isSaving());
let record=0,list=0,weightState;const weight=api.createNurseOkanSaveFlow_({call:async action=>{if(action==='health.weight.record'){record++;return {weightKg:55};}if(action==='health.weight.list'){list++;return {items:[{weightKg:55}]};}},onSaving:()=>{},onSuccess:async(action,data)=>{if(action==='health.weight.record'){list++;weightState={items:[{weightKg:55}]};}},onSaved:()=>{},onFailure:()=>{},onSettled:()=>{}});await weight.save('health.weight.record',{weightKg:55});assert.equal(record,1);assert.equal(list,1);assert.deepStrictEqual(weightState,{items:[{weightKg:55}]});
console.log('PASS nurse UI double-save, offline, failure retry, weight refresh, payload boundary, delayed initialization');}
run().catch(e=>{console.error(e);process.exitCode=1;});
