const SLOT = Object.freeze({
  morning: ['morningStaple','morningProteinSource','morningWater','morningMedication','morningCondition'], lunch: ['lunchAmount','lunchProteinSource','lunchWater'],
  post_training: ['postTrainingStatus','postTrainingOnigiriCount','postTrainingProteinSource'],
  dinner: ['dinnerRiceBowls','dinnerNattoPacks','dinnerExtraProteinSource','dinnerMedication','bedtime'],
  condition: ['conditionAppetite','conditionSymptomsJson','conditionNote'],
});
const SLOT_META = Object.freeze({
  morning:{id:'morningClientRequestId',by:'morningRecordedBy',at:'morningRecordedAt'}, lunch:{id:'lunchClientRequestId',by:'lunchRecordedBy',at:'lunchRecordedAt'},
  post_training:{id:'postTrainingClientRequestId',by:'postTrainingRecordedBy',at:'postTrainingRecordedAt'}, dinner:{id:'dinnerClientRequestId',by:'dinnerRecordedBy',at:'dinnerRecordedAt'}, condition:{id:'conditionClientRequestId',by:'conditionRecordedBy',at:'conditionRecordedAt'},
});
function healthMap_(sheet) { const values=sheet.getDataRange().getValues(), map={}; (values[0] || []).forEach(function(h,i){map[String(h)]=i;}); return {values:values,map:map}; }
function healthObject_(table,row) { const out={}; Object.keys(table.map).forEach(function(k){out[k]=row[table.map[k]];}); return out; }
function healthRow_(sheet,homeId,targetUserId,localDate) { const table=healthMap_(sheet); for(let i=1;i<table.values.length;i++) { const row=table.values[i]; if(String(row[table.map.homeId])===String(homeId)&&String(row[table.map.targetUserId])===String(targetUserId)&&healthDate_(row[table.map.localDate])===localDate) return {table:table,row:row.slice(),rowNumber:i+1}; } return {table:table,row:new Array((table.values[0]||[]).length).fill(''),rowNumber:0}; }
function dailyGet_(body) { validateDate_(body.localDate); const found=healthRow_(healthSheet_(HEALTH_SHEETS.daily),body.homeId,body.targetUserId,body.localDate); const row=healthObject_(found.table,found.row); return {localDate:body.localDate,slots:dailySlots_(row),ruleCodes:evaluateHealthRules_(row,weightItems_(body.homeId,body.targetUserId,20))}; }
function healthBoolean_(value) { return value === true || String(value).toLowerCase() === 'true'; }
function dailySlots_(row) { const out={}; Object.keys(SLOT).forEach(function(slot){const m=SLOT_META[slot]; if(row[m.at]) { out[slot]={}; SLOT[slot].forEach(function(k){out[slot][k]=k==='conditionSymptomsJson'?safeJsonArray_(row[k]):HEALTH_BOOLEAN_FIELDS[k]?healthBoolean_(row[k]):row[k];}); out[slot].recordedAt=row[m.at]; out[slot].recordedBy=row[m.by]; }}); return out; }
function dailyRecord_(body) { validateDaily_(body); const found=healthRow_(healthSheet_(HEALTH_SHEETS.daily),body.homeId,body.targetUserId,body.localDate), table=found.table,row=found.row,now=healthNow_(); const put=function(k,v){row[table.map[k]]=v;}; if(!found.rowNumber){put('recordId',Utilities.getUuid());put('homeId',body.homeId);put('targetUserId',body.targetUserId);put('localDate',body.localDate);put('createdAt',now);} const slot=body.slot, payload=body.payload, meta=SLOT_META[slot]; SLOT[slot].forEach(function(key){put(key,key==='conditionSymptomsJson'?JSON.stringify(payload.symptoms):key==='conditionNote'?String(payload.note || ''):payload[key]);}); put(meta.id,body.clientRequestId); put(meta.by,body.actorUserId); put(meta.at,now); put('updatedAt',now); healthSheet_(HEALTH_SHEETS.daily).getRange(found.rowNumber || healthSheet_(HEALTH_SHEETS.daily).getLastRow()+1,1,1,row.length).setValues([row]); return dailyGet_(body); }
function weightRecord_(body) { validateWeight_(body); const sheet=healthSheet_(HEALTH_SHEETS.weight),table=healthMap_(sheet),row=new Array(table.values[0].length).fill(''),put=function(k,v){row[table.map[k]]=v;}; [['recordId',Utilities.getUuid()],['homeId',body.homeId],['targetUserId',body.targetUserId],['measuredDate',body.measuredDate],['weightKg',Number(body.weightKg)],['source','manual'],['recordedBy',body.actorUserId],['recordedAt',healthNow_()],['clientRequestId',body.clientRequestId]].forEach(function(pair){put(pair[0],pair[1]);}); sheet.appendRow(row); return {measuredDate:body.measuredDate,weightKg:Number(body.weightKg)}; }
function weightItems_(homeId,targetUserId,limit) { const table=healthMap_(healthSheet_(HEALTH_SHEETS.weight)); return table.values.slice(1).filter(function(row){return String(row[table.map.homeId])===String(homeId)&&String(row[table.map.targetUserId])===String(targetUserId);}).sort(function(a,b){return healthDate_(b[table.map.measuredDate]).localeCompare(healthDate_(a[table.map.measuredDate]));}).slice(0,limit).map(function(row){return {measuredDate:healthDate_(row[table.map.measuredDate]),weightKg:Number(row[table.map.weightKg]),recordedAt:String(row[table.map.recordedAt]||'')};}); }
function weightList_(body) { const limit=body.limit === undefined ? 8 : Number(body.limit); if(!Number.isInteger(limit)||limit<1||limit>20) throw healthErr_('INVALID_INPUT'); return {items:weightItems_(body.homeId,body.targetUserId,limit)}; }
function healthContext_(body) { if(!body.homeId||!body.actorUserId||!body.targetUserId) throw healthErr_('INVALID_INPUT'); return {homeId:String(body.homeId),actor:{userId:String(body.actorUserId),role:String(body.actorRole || '')},targets:[{userId:String(body.targetUserId)}]}; }
function validateDate_(date) { if(!/^\d{4}-\d{2}-\d{2}$/.test(String(date||''))) throw healthErr_('INVALID_INPUT'); }
const HEALTH_BOOLEAN_FIELDS=Object.freeze({morningWater:true,morningMedication:true,morningCondition:true,lunchWater:true,dinnerMedication:true,bedtime:true});
function validateHealthBoolean_(value) { return typeof value === 'boolean'; }
function validateDaily_(b) { if(!healthUuid_(b.clientRequestId)||!SLOT[b.slot]) throw healthErr_('INVALID_INPUT'); validateDate_(b.localDate); const p=b.payload||{}; const oneOf=function(value,list){return list.indexOf(value)>=0;}; if(b.slot==='morning'&&(!oneOf(p.morningStaple,['none','small','normal'])||!oneOf(p.morningProteinSource,['none','egg','natto','dairy','tofu','fish','protein','other'])||!validateHealthBoolean_(p.morningWater)||!validateHealthBoolean_(p.morningMedication)||!validateHealthBoolean_(p.morningCondition)))throw healthErr_('INVALID_INPUT'); if(b.slot==='lunch'&&(!oneOf(p.lunchAmount,['none','half','most','all'])||!oneOf(p.lunchProteinSource,['none','included','unknown'])||!validateHealthBoolean_(p.lunchWater)))throw healthErr_('INVALID_INPUT'); if(b.slot==='post_training'&&(!oneOf(p.postTrainingStatus,['recorded','rest_day'])||!Number.isInteger(Number(p.postTrainingOnigiriCount))||Number(p.postTrainingOnigiriCount)<0||Number(p.postTrainingOnigiriCount)>10||!oneOf(p.postTrainingProteinSource,['none','protein','milk','yogurt','soy','other'])))throw healthErr_('INVALID_INPUT'); if(b.slot==='dinner'&&(!Number.isInteger(Number(p.dinnerRiceBowls))||Number(p.dinnerRiceBowls)<0||Number(p.dinnerRiceBowls)>10||!Number.isInteger(Number(p.dinnerNattoPacks))||Number(p.dinnerNattoPacks)<0||Number(p.dinnerNattoPacks)>10||!oneOf(p.dinnerExtraProteinSource,['none','egg','dairy','tofu','fish','protein','other'])||!validateHealthBoolean_(p.dinnerMedication)||!validateHealthBoolean_(p.bedtime)))throw healthErr_('INVALID_INPUT'); if(b.slot==='condition'&&(!oneOf(p.conditionAppetite,['good','normal','low'])||!Array.isArray(p.symptoms)||p.symptoms.some(function(x){return ['dizziness','headache','nausea','cramps','marked_fatigue'].indexOf(x)<0;})||String(p.note||'').length>200))throw healthErr_('INVALID_INPUT'); }
function validateWeight_(b) { if(!healthUuid_(b.clientRequestId)||!Number.isFinite(Number(b.weightKg))||Number(b.weightKg)<20||Number(b.weightKg)>200)throw healthErr_('INVALID_INPUT');validateDate_(b.measuredDate); }
function safeJsonArray_(value){try{const out=JSON.parse(value||'[]');return Array.isArray(out)?out:[];}catch(_){return [];}}
function healthDate_(value){if(Object.prototype.toString.call(value)==='[object Date]'&&!isNaN(value))return Utilities.formatDate(value,'Asia/Tokyo','yyyy-MM-dd');const s=String(value||'');return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:'';}
