const SLOT = Object.freeze({
  morning: ['morningStaple','morningProteinSource','morningWater','morningMedication','morningCondition','morningMealType','morningMealOther','morningWaterType','morningWaterOther','morningConditionType','morningConditionOther'], lunch: ['lunchAmount','lunchProteinSource','lunchWater','lunchCondition','lunchMealType','lunchMealOther','lunchWaterType','lunchWaterOther','lunchConditionType','lunchConditionOther'],
  post_training: ['postTrainingStatus','postTrainingOnigiriCount','postTrainingProteinSource','postTrainingWater','postTrainingCondition','postTrainingSnackType','postTrainingSnackOther','postTrainingWaterType','postTrainingWaterOther','postTrainingProteinAmount','postTrainingProteinOther','postTrainingConditionType','postTrainingConditionOther'],
  dinner: ['dinnerRiceBowls','dinnerNattoPacks','dinnerExtraProteinSource','dinnerMedication','bedtime','dinnerMealType','dinnerMealOther'],
  condition: ['conditionAppetite','conditionSymptomsJson','conditionNote'],
});
const SLOT_META = Object.freeze({
  morning:{id:'morningClientRequestId',by:'morningRecordedBy',at:'morningRecordedAt'}, lunch:{id:'lunchClientRequestId',by:'lunchRecordedBy',at:'lunchRecordedAt'},
  post_training:{id:'postTrainingClientRequestId',by:'postTrainingRecordedBy',at:'postTrainingRecordedAt'}, dinner:{id:'dinnerClientRequestId',by:'dinnerRecordedBy',at:'dinnerRecordedAt'}, condition:{id:'conditionClientRequestId',by:'conditionRecordedBy',at:'conditionRecordedAt'},
});
function healthMap_(sheet) { const values=sheet.getDataRange().getValues(), map={}; (values[0] || []).forEach(function(h,i){map[String(h)]=i;}); return {values:values,map:map}; }
function healthObject_(table,row) { const out={}; Object.keys(table.map).forEach(function(k){out[k]=row[table.map[k]];}); return out; }
function healthRow_(sheet,homeId,targetUserId,localDate) { const table=healthMap_(sheet); for(let i=1;i<table.values.length;i++) { const row=table.values[i]; if(String(row[table.map.homeId])===String(homeId)&&String(row[table.map.targetUserId])===String(targetUserId)&&healthDate_(row[table.map.localDate])===localDate) return {table:table,row:row.slice(),rowNumber:i+1}; } return {table:table,row:new Array((table.values[0]||[]).length).fill(''),rowNumber:0}; }
function emptyDaily_(body) { return {localDate:body.localDate,slots:{},ruleCodes:evaluateHealthRules_({},weightItems_(body.homeId,body.targetUserId,20))}; }
function dailyGet_(body) { validateDate_(body.localDate); const found=healthRow_(healthSheet_(HEALTH_SHEETS.daily),body.homeId,body.targetUserId,body.localDate); if(!found.rowNumber)return emptyDaily_(body); const row=healthObject_(found.table,found.row); return {localDate:body.localDate,slots:dailySlots_(row),ruleCodes:evaluateHealthRules_(row,weightItems_(body.homeId,body.targetUserId,20))}; }
function healthBoolean_(value) { return value === true || String(value).toLowerCase() === 'true'; }
function dailySlots_(row) { const out={}; Object.keys(SLOT).forEach(function(slot){const m=SLOT_META[slot]; if(row[m.at]) { out[slot]={}; SLOT[slot].forEach(function(k){out[slot][k]=k==='conditionSymptomsJson'?safeJsonArray_(row[k]):HEALTH_BOOLEAN_FIELDS[k]?healthBoolean_(row[k]):row[k];}); out[slot].recordedAt=row[m.at]; out[slot].recordedBy=row[m.by]; }}); return out; }
function dailyRecord_(body) { validateDaily_(body); const found=healthRow_(healthSheet_(HEALTH_SHEETS.daily),body.homeId,body.targetUserId,body.localDate), table=found.table,row=found.row,now=healthNow_(); const put=function(k,v){row[table.map[k]]=v;}; if(!found.rowNumber){put('recordId',Utilities.getUuid());put('homeId',body.homeId);put('targetUserId',body.targetUserId);put('localDate',body.localDate);put('createdAt',now);} const slot=body.slot, payload=body.payload, meta=SLOT_META[slot]; SLOT[slot].forEach(function(key){if(!Object.prototype.hasOwnProperty.call(payload,key))return;put(key,key==='conditionSymptomsJson'?JSON.stringify(payload.symptoms):key==='conditionNote'?String(payload.note || ''):payload[key]);}); put(meta.id,body.clientRequestId); put(meta.by,body.actorUserId); put(meta.at,now); put('updatedAt',now); healthSheet_(HEALTH_SHEETS.daily).getRange(found.rowNumber || healthSheet_(HEALTH_SHEETS.daily).getLastRow()+1,1,1,row.length).setValues([row]); return dailyGet_(body); }
function weightRecord_(body) { validateWeight_(body); const sheet=healthSheet_(HEALTH_SHEETS.weight),table=healthMap_(sheet),row=new Array(table.values[0].length).fill(''),put=function(k,v){row[table.map[k]]=v;}; [['recordId',Utilities.getUuid()],['homeId',body.homeId],['targetUserId',body.targetUserId],['measuredDate',body.measuredDate],['weightKg',Number(body.weightKg)],['source','manual'],['recordedBy',body.actorUserId],['recordedAt',healthNow_()],['clientRequestId',body.clientRequestId]].forEach(function(pair){put(pair[0],pair[1]);}); sheet.appendRow(row); return {measuredDate:body.measuredDate,weightKg:Number(body.weightKg)}; }
function weightItems_(homeId,targetUserId,limit) { const table=healthMap_(healthSheet_(HEALTH_SHEETS.weight)); return table.values.slice(1).filter(function(row){return String(row[table.map.homeId])===String(homeId)&&String(row[table.map.targetUserId])===String(targetUserId);}).sort(function(a,b){return healthDate_(b[table.map.measuredDate]).localeCompare(healthDate_(a[table.map.measuredDate]));}).slice(0,limit).map(function(row){return {measuredDate:healthDate_(row[table.map.measuredDate]),weightKg:Number(row[table.map.weightKg]),recordedAt:String(row[table.map.recordedAt]||'')};}); }
function weightList_(body) { const limit=body.limit === undefined ? 8 : Number(body.limit); if(!Number.isInteger(limit)||limit<1||limit>20) throw healthErr_('INVALID_INPUT'); return {items:weightItems_(body.homeId,body.targetUserId,limit)}; }
function healthContext_(body) { if(!body.homeId||!body.actorUserId||!body.targetUserId) throw healthErr_('INVALID_INPUT'); return {homeId:String(body.homeId),actor:{userId:String(body.actorUserId),role:String(body.actorRole || '')},targets:[{userId:String(body.targetUserId)}]}; }
function validateDate_(date) { if(!/^\d{4}-\d{2}-\d{2}$/.test(String(date||''))) throw healthErr_('INVALID_INPUT'); }
const HEALTH_BOOLEAN_FIELDS=Object.freeze({morningWater:true,morningMedication:true,morningCondition:true,lunchWater:true,lunchCondition:true,postTrainingWater:true,postTrainingCondition:true,dinnerMedication:true,bedtime:true});
const HEALTH_OPTIONAL_SLOT_FIELDS=Object.freeze({morningWater:true,morningMedication:true,morningCondition:true,lunchWater:true,lunchCondition:true,postTrainingWater:true,postTrainingCondition:true,dinnerMedication:true,bedtime:true,morningMealType:true,morningMealOther:true,morningWaterType:true,morningWaterOther:true,morningConditionType:true,morningConditionOther:true,lunchMealType:true,lunchMealOther:true,lunchWaterType:true,lunchWaterOther:true,lunchConditionType:true,lunchConditionOther:true,postTrainingSnackType:true,postTrainingSnackOther:true,postTrainingWaterType:true,postTrainingWaterOther:true,postTrainingProteinAmount:true,postTrainingProteinOther:true,postTrainingConditionType:true,postTrainingConditionOther:true,dinnerMealType:true,dinnerMealOther:true});
function validateHealthBoolean_(value) { return typeof value === 'boolean'; }
function validateOptionalHealthBoolean_(payload,key) { return !hasHealthField_(payload,key) || validateHealthBoolean_(payload[key]); }
const HEALTH_CONTENT_OPTIONS=Object.freeze({morningMealType:['banana_1','rice_1','rice_2','bread_1','bread_2','cereal_1','yogurt_1','other'],morningWaterType:['milk_glass_1','water_glass_1','water_bottle_1','tea_glass_1','tea_bottle_1','sports_drink_bottle_1','juice_glass_1','other'],conditionType:['good','slight_fever','fever','fatigue','cough','throat','nose','headache','stomachache','nausea','muscle_pain','other'],lunchMealType:['bento','cafeteria','convenience_bento','onigiri','bread','noodles','other'],lunchWaterType:['sports_drink_bottle_1','sports_drink_bottle_2','water_bottle_1','tea_bottle_1','juice_bottle_1','other'],postTrainingSnackType:['onigiri_1','onigiri_2','onigiri_3','bread_1','bread_2','banana_1','jelly_1','other'],postTrainingProteinAmount:['15','20','25','30','40','other'],dinnerMealType:['rice_1','rice_2','rice_3','rice_1_natto','rice_2_natto','rice_2_tofu','rice_2_natto_tofu','rice_2_natto_kimchi','rice_2_natto_tofu_kimchi','rice_2_meat','rice_2_fish','rice_2_meat_natto','rice_2_fish_natto','noodles','other']});
function hasHealthField_(object,key){return Object.prototype.hasOwnProperty.call(object||{},key);}
function validateContentField_(payload,typeKey,otherKey,options,required){if(!hasHealthField_(payload,typeKey)){if(required)throw healthErr_('INVALID_INPUT');return;}const type=String(payload[typeKey]||'');if(options.indexOf(type)<0)throw healthErr_('INVALID_INPUT');const other=hasHealthField_(payload,otherKey)?String(payload[otherKey]||'').trim():'';if(other.length>100)throw healthErr_('INVALID_INPUT');if(type==='other'&&!other)throw healthErr_('INVALID_INPUT');}
function validateSlotContent_(slot,payload){if(slot==='morning'){validateContentField_(payload,'morningMealType','morningMealOther',HEALTH_CONTENT_OPTIONS.morningMealType,payload.morningStaple!=='none');validateContentField_(payload,'morningWaterType','morningWaterOther',HEALTH_CONTENT_OPTIONS.morningWaterType,payload.morningWater);validateContentField_(payload,'morningConditionType','morningConditionOther',HEALTH_CONTENT_OPTIONS.conditionType,payload.morningCondition);return;}if(slot==='lunch'){validateContentField_(payload,'lunchMealType','lunchMealOther',HEALTH_CONTENT_OPTIONS.lunchMealType,payload.lunchAmount!=='none');validateContentField_(payload,'lunchWaterType','lunchWaterOther',HEALTH_CONTENT_OPTIONS.lunchWaterType,payload.lunchWater);validateContentField_(payload,'lunchConditionType','lunchConditionOther',HEALTH_CONTENT_OPTIONS.conditionType,payload.lunchCondition);return;}if(slot==='post_training'){validateContentField_(payload,'postTrainingSnackType','postTrainingSnackOther',HEALTH_CONTENT_OPTIONS.postTrainingSnackType,Number(payload.postTrainingOnigiriCount)>0);validateContentField_(payload,'postTrainingWaterType','postTrainingWaterOther',HEALTH_CONTENT_OPTIONS.lunchWaterType,payload.postTrainingWater);validateContentField_(payload,'postTrainingProteinAmount','postTrainingProteinOther',HEALTH_CONTENT_OPTIONS.postTrainingProteinAmount,payload.postTrainingProteinSource!=='none');validateContentField_(payload,'postTrainingConditionType','postTrainingConditionOther',HEALTH_CONTENT_OPTIONS.conditionType,payload.postTrainingCondition);return;}if(slot==='dinner')validateContentField_(payload,'dinnerMealType','dinnerMealOther',HEALTH_CONTENT_OPTIONS.dinnerMealType,Number(payload.dinnerRiceBowls)>0);}
function validateDaily_(b) { if(!healthUuid_(b.clientRequestId)||!SLOT[b.slot]) throw healthErr_('INVALID_INPUT'); validateDate_(b.localDate); const p=b.payload||{}; const oneOf=function(value,list){return list.indexOf(value)>=0;}; if(b.slot==='morning'&&(!oneOf(p.morningStaple,['none','small','normal'])||!oneOf(p.morningProteinSource,['none','egg','natto','dairy','tofu','fish','protein','other'])||!validateOptionalHealthBoolean_(p,'morningWater')||!validateOptionalHealthBoolean_(p,'morningMedication')||!validateOptionalHealthBoolean_(p,'morningCondition')))throw healthErr_('INVALID_INPUT'); if(b.slot==='lunch'&&(!oneOf(p.lunchAmount,['none','half','most','all'])||!oneOf(p.lunchProteinSource,['none','included','unknown'])||!validateOptionalHealthBoolean_(p,'lunchWater')||!validateOptionalHealthBoolean_(p,'lunchCondition')))throw healthErr_('INVALID_INPUT'); if(b.slot==='post_training'&&(!oneOf(p.postTrainingStatus,['recorded','rest_day'])||!Number.isInteger(Number(p.postTrainingOnigiriCount))||Number(p.postTrainingOnigiriCount)<0||Number(p.postTrainingOnigiriCount)>10||!oneOf(p.postTrainingProteinSource,['none','protein','milk','yogurt','soy','other'])||!validateOptionalHealthBoolean_(p,'postTrainingWater')||!validateOptionalHealthBoolean_(p,'postTrainingCondition')))throw healthErr_('INVALID_INPUT'); if(b.slot==='dinner'&&(!Number.isInteger(Number(p.dinnerRiceBowls))||Number(p.dinnerRiceBowls)<0||Number(p.dinnerRiceBowls)>10||!Number.isInteger(Number(p.dinnerNattoPacks))||Number(p.dinnerNattoPacks)<0||Number(p.dinnerNattoPacks)>10||!oneOf(p.dinnerExtraProteinSource,['none','egg','dairy','tofu','fish','protein','other'])||!validateOptionalHealthBoolean_(p,'dinnerMedication')||!validateOptionalHealthBoolean_(p,'bedtime')))throw healthErr_('INVALID_INPUT'); if(b.slot==='condition'&&(!oneOf(p.conditionAppetite,['good','normal','low'])||!Array.isArray(p.symptoms)||p.symptoms.some(function(x){return ['dizziness','headache','nausea','cramps','marked_fatigue'].indexOf(x)<0;})||String(p.note||'').length>200))throw healthErr_('INVALID_INPUT'); validateSlotContent_(b.slot,p); }
function validateWeight_(b) { if(!healthUuid_(b.clientRequestId)||!Number.isFinite(Number(b.weightKg))||Number(b.weightKg)<20||Number(b.weightKg)>200)throw healthErr_('INVALID_INPUT');validateDate_(b.measuredDate); }
function safeJsonArray_(value){try{const out=JSON.parse(value||'[]');return Array.isArray(out)?out:[];}catch(_){return [];}}
function healthDate_(value){if(Object.prototype.toString.call(value)==='[object Date]'&&!isNaN(value))return Utilities.formatDate(value,'Asia/Tokyo','yyyy-MM-dd');const s=String(value||'');return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:'';}
