const SLOT = Object.freeze({
  morning: ['morningStaple','morningProteinSource','morningWater','morningMedication','morningCondition','morningMealType','morningMealOther','morningWaterType','morningWaterOther','morningConditionType','morningConditionOther'], lunch: ['lunchAmount','lunchProteinSource','lunchWater','lunchCondition','lunchMealType','lunchMealOther','lunchWaterType','lunchWaterOther','lunchConditionType','lunchConditionOther'],
  post_training: ['postTrainingStatus','postTrainingOnigiriCount','postTrainingProteinSource','postTrainingWater','postTrainingCondition','postTrainingSnackType','postTrainingSnackOther','postTrainingWaterType','postTrainingWaterOther','postTrainingProteinAmount','postTrainingProteinOther','postTrainingConditionType','postTrainingConditionOther'],
  dinner: ['dinnerRiceBowls','dinnerNattoPacks','dinnerExtraProteinSource','dinnerMedication','bedtime','dinnerMealType','dinnerMealOther'],
  condition: ['conditionAppetite','conditionSymptomsJson','conditionNote'],
});
const SLOT_META = Object.freeze({
  morning:{id:'morningClientRequestId',by:'morningRecordedBy',at:'morningRecordedAt'}, lunch:{id:'lunchClientRequestId',by:'lunchRecordedBy',at:'lunchRecordedAt'},
  post_training:{id:'postTrainingClientRequestId',by:'postTrainingRecordedBy',at:'postTrainingRecordedAt'}, dinner:{id:'dinnerClientRequestId',by:'dinnerRecordedBy',at:'dinnerRecordedAt'}, condition:{id:'conditionClientRequestId',by:'conditionRecordedBy',at:'conditionRecordedAt'},
});
function healthMap_(sheet) { const values=sheet.getDataRange().getValues(), map={}; (values[0] || []).forEach(function(h,i){map[String(h)]=i;}); return {values:values,map:map}; }
function healthObject_(table,row) { const out={}; Object.keys(table.map).forEach(function(k){out[k]=row[table.map[k]];}); return out; }
function healthRow_(sheet,homeId,targetUserId,localDate) { const table=healthMap_(sheet); for(let i=1;i<table.values.length;i++) { const row=table.values[i]; if(String(row[table.map.homeId])===String(homeId)&&String(row[table.map.targetUserId])===String(targetUserId)&&healthDate_(row[table.map.localDate])===localDate) return {table:table,row:row.slice(),rowNumber:i+1}; } return {table:table,row:new Array((table.values[0]||[]).length).fill(''),rowNumber:0}; }
function emptyDaily_(body) { return {localDate:body.localDate,slots:{},ruleCodes:evaluateHealthRules_({},weightItems_(body.homeId,body.targetUserId,20))}; }
function dailyGet_(body) { validateDate_(body.localDate); const found=healthRow_(healthSheet_(HEALTH_SHEETS.daily),body.homeId,body.targetUserId,body.localDate); if(!found.rowNumber)return emptyDaily_(body); const row=healthObject_(found.table,found.row); return {localDate:body.localDate,slots:dailySlots_(row),ruleCodes:evaluateHealthRules_(row,weightItems_(body.homeId,body.targetUserId,20))}; }
const HEALTH_DAILY_LIST_MAX_DAYS = 31;
const HEALTH_WEIGHT_LIST_MAX_DAYS = 31;
function healthLocalDateUtc_(value) { validateDate_(value); const parts=String(value).split('-').map(Number),date=new Date(Date.UTC(parts[0],parts[1]-1,parts[2])); if(date.getUTCFullYear()!==parts[0]||date.getUTCMonth()!==parts[1]-1||date.getUTCDate()!==parts[2])throw healthErr_('INVALID_INPUT'); return date; }
function healthUtcDateText_(date) { return [date.getUTCFullYear(),String(date.getUTCMonth()+1).padStart(2,'0'),String(date.getUTCDate()).padStart(2,'0')].join('-'); }
function dailyList_(body) { const from=healthLocalDateUtc_(body.fromLocalDate),to=healthLocalDateUtc_(body.toLocalDate),fromTime=from.getTime(),toTime=to.getTime(),dayCount=Math.floor((toTime-fromTime)/86400000)+1; if(fromTime>toTime||dayCount>HEALTH_DAILY_LIST_MAX_DAYS)throw healthErr_('INVALID_INPUT'); const table=healthMap_(healthSheet_(HEALTH_SHEETS.daily)),weights=weightItems_(body.homeId,body.targetUserId,20),rowsByDate={}; table.values.slice(1).forEach(function(row){const localDate=healthDate_(row[table.map.localDate]);if(String(row[table.map.homeId])!==String(body.homeId)||String(row[table.map.targetUserId])!==String(body.targetUserId)||localDate<body.fromLocalDate||localDate>body.toLocalDate||Object.prototype.hasOwnProperty.call(rowsByDate,localDate))return;rowsByDate[localDate]=healthObject_(table,row);}); const items=[]; for(let offset=0;offset<dayCount;offset++){const date=new Date(fromTime+offset*86400000),localDate=healthUtcDateText_(date),row=rowsByDate[localDate];items.push({localDate:localDate,slots:row?dailySlots_(row):{},ruleCodes:evaluateHealthRules_(row||{},weights)});} return {items:items}; }
function healthBoolean_(value) { return value === true || String(value).toLowerCase() === 'true'; }
function dailySlotFromRow_(row,slot) { const m=SLOT_META[slot]; if(!row||!row[m.at])return null; const out={}; SLOT[slot].forEach(function(k){out[k]=k==='conditionSymptomsJson'?safeJsonArray_(row[k]):HEALTH_BOOLEAN_FIELDS[k]?healthBoolean_(row[k]):row[k];}); out.recordedAt=row[m.at]; out.recordedBy=row[m.by]; return out; }
function dailySlots_(row) { const out={}; Object.keys(SLOT).forEach(function(slot){const value=dailySlotFromRow_(row,slot);if(value)out[slot]=value;}); return out; }
function dailyPayloadCell_(key,payload) { if(key==='conditionSymptomsJson')return JSON.stringify(payload.symptoms); if(key==='conditionNote')return String(payload.note||''); return Object.prototype.hasOwnProperty.call(payload,key)?payload[key]:''; }
function dailyWritePlan_(body,now) { validateDaily_(body); const sheet=healthSheet_(HEALTH_SHEETS.daily),found=healthRow_(sheet,body.homeId,body.targetUserId,body.localDate),table=found.table,row=found.row,put=function(k,v){row[table.map[k]]=v;}; if(!found.rowNumber){put('recordId',Utilities.getUuid());put('homeId',body.homeId);put('targetUserId',body.targetUserId);put('localDate',body.localDate);put('createdAt',now);} const slot=body.slot,meta=SLOT_META[slot],before=dailySlotFromRow_(healthObject_(table,row),slot),replace=body.isCorrection===true; SLOT[slot].forEach(function(key){if(!replace&&!Object.prototype.hasOwnProperty.call(body.payload,key))return;put(key,dailyPayloadCell_(key,body.payload));}); put(meta.id,body.clientRequestId);put(meta.by,body.actorUserId);put(meta.at,now);put('updatedAt',now);const after=dailySlotFromRow_(healthObject_(table,row),slot);return {body:body,sheet:sheet,table:table,row:row,rowNumber:found.rowNumber||sheet.getLastRow()+1,slot:slot,now:now,before:before,after:after}; }
function dailyApplyWritePlan_(plan) { plan.sheet.getRange(plan.rowNumber,1,1,plan.row.length).setValues([plan.row]); }
function dailyRecord_(body) { const plan=dailyWritePlan_(body,healthNow_());dailyApplyWritePlan_(plan);return dailyGet_(body); }
function weightStatus_(row) { const value=String(row&&row.status||'').trim();return value||'active'; }
function weightPublic_(row) { return {recordId:String(row.recordId||''),measuredDate:healthDate_(row.measuredDate),weightKg:Number(row.weightKg),recordedAt:String(row.recordedAt||'')}; }
function weightAppend_(body,values) { const sheet=healthSheet_(HEALTH_SHEETS.weight),table=healthMap_(sheet),row=new Array(table.values[0].length).fill(''),put=function(k,v){row[table.map[k]]=v;};Object.keys(values).forEach(function(key){put(key,values[key]);});sheet.appendRow(row);return {sheet:sheet,table:table,row:healthObject_(table,row),rowNumber:sheet.getLastRow()}; }
function weightRecord_(body) { validateWeight_(body);const now=healthNow_(),stored=weightAppend_(body,{recordId:Utilities.getUuid(),homeId:body.homeId,targetUserId:body.targetUserId,measuredDate:body.measuredDate,weightKg:Number(body.weightKg),source:'manual',recordedBy:body.actorUserId,recordedAt:now,clientRequestId:body.clientRequestId,status:'active',correctionOfRecordId:'',correctionReason:''});return weightPublic_(stored.row); }
function weightRecordById_(homeId,targetUserId,recordId) { const sheet=healthSheet_(HEALTH_SHEETS.weight),table=healthMap_(sheet);for(let index=1;index<table.values.length;index++){const row=table.values[index];if(String(row[table.map.recordId]||'')===String(recordId||'')&&String(row[table.map.homeId]||'')===String(homeId||'')&&String(row[table.map.targetUserId]||'')===String(targetUserId||''))return {sheet:sheet,table:table,row:healthObject_(table,row),rowNumber:index+1};}return null; }
function weightSetStatus_(found,status) { found.sheet.getRange(found.rowNumber,found.table.map.status+1,1,1).setValues([[status]]);found.row.status=status; }
function weightRequestById_(clientRequestId) { const sheet=healthSheet_(HEALTH_SHEETS.weight),table=healthMap_(sheet),matches=[];table.values.slice(1).forEach(function(row,index){if(String(row[table.map.clientRequestId]||'')===String(clientRequestId||''))matches.push({sheet:sheet,table:table,row:healthObject_(table,row),rawRow:row,rowNumber:index+2});});if(matches.length>1)throw healthErr_('DATA_INTEGRITY_ERROR');return matches[0]||null; }
function weightCorrectionSibling_(sourceRecordId,excludeRecordId) { const sheet=healthSheet_(HEALTH_SHEETS.weight),table=healthMap_(sheet);return table.values.slice(1).map(function(row,index){return {row:healthObject_(table,row),rowNumber:index+2};}).find(function(found){const status=weightStatus_(found.row);return String(found.row.correctionOfRecordId||'')===String(sourceRecordId||'')&&String(found.row.recordId||'')!==String(excludeRecordId||'')&&(status==='pending'||status==='active');})||null; }
function validateWeightCorrection_(body) { validateWeight_(body);if(!healthUuid_(body.recordId))throw healthErr_('INVALID_INPUT');normalizeCorrectionReason_(body.correctionReason); }
function weightCorrect_(body) { validateWeightCorrection_(body);const source=weightRecordById_(body.homeId,body.targetUserId,body.recordId);if(!source||weightStatus_(source.row)!=='active'||weightCorrectionSibling_(source.row.recordId,''))throw healthErr_('INVALID_INPUT');const now=healthNow_(),reason=normalizeCorrectionReason_(body.correctionReason),stored=weightAppend_(body,{recordId:Utilities.getUuid(),homeId:body.homeId,targetUserId:body.targetUserId,measuredDate:body.measuredDate,weightKg:Number(body.weightKg),source:'manual_correction',recordedBy:body.actorUserId,recordedAt:now,clientRequestId:body.clientRequestId,status:'pending',correctionOfRecordId:source.row.recordId,correctionReason:reason});weightSetStatus_(source,'corrected');weightSetStatus_(stored,'active');const result=weightPublic_(stored.row);result.correctionOfRecordId=source.row.recordId;return result; }
function weightRecoverCorrection_(body, stored) { const child=weightRecordById_(body.homeId,body.targetUserId,stored.row.recordId),source=weightRecordById_(body.homeId,body.targetUserId,body.recordId);if(!child||!source||String(child.row.correctionOfRecordId||'')!==String(body.recordId||'')||weightCorrectionSibling_(body.recordId,child.row.recordId))throw healthErr_('DATA_INTEGRITY_ERROR');const childStatus=weightStatus_(child.row),sourceStatus=weightStatus_(source.row);if(childStatus==='pending'){if(sourceStatus==='active')weightSetStatus_(source,'corrected');else if(sourceStatus!=='corrected')throw healthErr_('DATA_INTEGRITY_ERROR');weightSetStatus_(child,'active');}else if(childStatus!=='active'||sourceStatus!=='corrected')throw healthErr_('DATA_INTEGRITY_ERROR');const result=weightPublic_(child.row);result.correctionOfRecordId=source.row.recordId;return result; }
function weightActiveRows_(homeId,targetUserId) { const table=healthMap_(healthSheet_(HEALTH_SHEETS.weight)); return table.values.slice(1).map(function(row){return healthObject_(table,row);}).filter(function(row){return String(row.homeId)===String(homeId)&&String(row.targetUserId)===String(targetUserId)&&weightStatus_(row)==='active';}).sort(function(a,b){return healthDate_(b.measuredDate).localeCompare(healthDate_(a.measuredDate))||String(b.recordedAt||'').localeCompare(String(a.recordedAt||''))||String(b.recordId||'').localeCompare(String(a.recordId||''));}); }
function weightItems_(homeId,targetUserId,limit) { return weightActiveRows_(homeId,targetUserId).slice(0,limit).map(weightPublic_); }
function weightListRange_(body) { const hasFrom=Object.prototype.hasOwnProperty.call(body||{},'fromLocalDate')&&String(body.fromLocalDate||'').trim()!==''; const hasTo=Object.prototype.hasOwnProperty.call(body||{},'toLocalDate')&&String(body.toLocalDate||'').trim()!==''; if(!hasFrom&&!hasTo)return null; if(!hasFrom||!hasTo)throw healthErr_('INVALID_INPUT'); const from=healthLocalDateUtc_(body.fromLocalDate),to=healthLocalDateUtc_(body.toLocalDate),fromTime=from.getTime(),toTime=to.getTime(),days=Math.floor((toTime-fromTime)/86400000)+1; if(fromTime>toTime||days>HEALTH_WEIGHT_LIST_MAX_DAYS)throw healthErr_('INVALID_INPUT'); return {fromLocalDate:healthUtcDateText_(from),toLocalDate:healthUtcDateText_(to)}; }
function weightList_(body) { const range=weightListRange_(body); if(range){const active=weightActiveRows_(body.homeId,body.targetUserId),items=active.filter(function(row){const date=healthDate_(row.measuredDate);return date>=range.fromLocalDate&&date<=range.toLocalDate;}).map(weightPublic_); return {items:items,latest:active.length?weightPublic_(active[0]):null,previous:active.length>1?weightPublic_(active[1]):null};} const limit=body.limit === undefined ? 8 : Number(body.limit); if(!Number.isInteger(limit)||limit<1||limit>20) throw healthErr_('INVALID_INPUT'); return {items:weightItems_(body.homeId,body.targetUserId,limit)}; }
function normalizeTargetWeightKg_(value) { const weight=Number(value),rounded=Math.round(weight*10)/10;if(!Number.isFinite(weight)||weight<20||weight>200||Math.abs(weight-rounded)>1e-9)throw healthErr_('INVALID_INPUT');return rounded; }
function healthProfileRow_(homeId,targetUserId) { if(!String(homeId||'').trim()||!String(targetUserId||'').trim())throw healthErr_('INVALID_INPUT');const sheet=healthSheet_(HEALTH_SHEETS.profile),table=healthMap_(sheet),matches=[];table.values.slice(1).forEach(function(row,index){if(String(row[table.map.homeId]||'')===String(homeId)&&String(row[table.map.targetUserId]||'')===String(targetUserId))matches.push({sheet:sheet,table:table,row:row.slice(),rowNumber:index+2});});if(matches.length>1)throw healthErr_('DATA_INTEGRITY_ERROR');return matches[0]||{sheet:sheet,table:table,row:new Array((table.values[0]||[]).length).fill(''),rowNumber:0}; }
function healthProfilePublic_(found) { if(!found||!found.rowNumber)return {targetWeightKg:null,updatedAt:null};const row=healthObject_(found.table,found.row),raw=row.targetWeightKg;if(raw===''||raw===null||raw===undefined)throw healthErr_('DATA_INTEGRITY_ERROR');let targetWeightKg;try{targetWeightKg=normalizeTargetWeightKg_(raw);}catch(_){throw healthErr_('DATA_INTEGRITY_ERROR');}return {targetWeightKg:targetWeightKg,updatedAt:String(row.updatedAt||'')||null}; }
function healthProfileGet_(body) { return healthProfilePublic_(healthProfileRow_(body.homeId,body.targetUserId)); }
function healthProfileUpdate_(body) { if(!healthUuid_(body.clientRequestId))throw healthErr_('INVALID_INPUT');const targetWeightKg=normalizeTargetWeightKg_(body.targetWeightKg),found=healthProfileRow_(body.homeId,body.targetUserId),now=healthNow_(),row=found.row,put=function(key,value){row[found.table.map[key]]=value;};if(!found.rowNumber){put('homeId',body.homeId);put('targetUserId',body.targetUserId);put('createdAt',now);}put('targetWeightKg',targetWeightKg);put('updatedBy',body.actorUserId);put('updatedAt',now);found.sheet.getRange(found.rowNumber||found.sheet.getLastRow()+1,1,1,row.length).setValues([row]);return healthProfileGet_(body); }
function healthContext_(body) { if(!body.homeId||!body.actorUserId||!body.targetUserId) throw healthErr_('INVALID_INPUT'); return {homeId:String(body.homeId),actor:{userId:String(body.actorUserId),role:String(body.actorRole || '')},targets:[{userId:String(body.targetUserId)}]}; }
function validateDate_(date) { if(!/^\d{4}-\d{2}-\d{2}$/.test(String(date||''))) throw healthErr_('INVALID_INPUT'); }
const HEALTH_BOOLEAN_FIELDS=Object.freeze({morningWater:true,morningMedication:true,morningCondition:true,lunchWater:true,lunchCondition:true,postTrainingWater:true,postTrainingCondition:true,dinnerMedication:true,bedtime:true});
const HEALTH_OPTIONAL_SLOT_FIELDS=Object.freeze({morningWater:true,morningMedication:true,morningCondition:true,lunchWater:true,lunchCondition:true,postTrainingWater:true,postTrainingCondition:true,dinnerMedication:true,bedtime:true,morningMealType:true,morningMealOther:true,morningWaterType:true,morningWaterOther:true,morningConditionType:true,morningConditionOther:true,lunchMealType:true,lunchMealOther:true,lunchWaterType:true,lunchWaterOther:true,lunchConditionType:true,lunchConditionOther:true,postTrainingSnackType:true,postTrainingSnackOther:true,postTrainingWaterType:true,postTrainingWaterOther:true,postTrainingProteinAmount:true,postTrainingProteinOther:true,postTrainingConditionType:true,postTrainingConditionOther:true,dinnerMealType:true,dinnerMealOther:true});
function validateHealthBoolean_(value) { return typeof value === 'boolean'; }
function validateOptionalHealthBoolean_(payload,key) { return !hasHealthField_(payload,key) || validateHealthBoolean_(payload[key]); }
const HEALTH_CONTENT_OPTIONS=Object.freeze({morningMealType:['banana_1','rice_1','rice_2','bread_1','bread_2','cereal_1','yogurt_1','other'],morningWaterType:['milk_glass_1','water_glass_1','water_bottle_1','tea_glass_1','tea_bottle_1','sports_drink_bottle_1','juice_glass_1','other'],conditionType:['good','slight_fever','fever','fatigue','cough','throat','nose','headache','stomachache','nausea','muscle_pain','other'],lunchMealType:['bento','cafeteria','convenience_bento','onigiri','bread','noodles','other'],lunchWaterType:['sports_drink_bottle_1','sports_drink_bottle_2','water_bottle_1','tea_bottle_1','juice_bottle_1','other'],postTrainingSnackType:['onigiri_1','onigiri_2','onigiri_3','bread_1','bread_2','banana_1','jelly_1','other'],postTrainingProteinAmount:['15','20','25','30','40','other'],dinnerMealType:['rice_1','rice_2','rice_3','rice_1_natto','rice_2_natto','rice_2_tofu','rice_2_natto_tofu','rice_2_natto_kimchi','rice_2_natto_tofu_kimchi','rice_2_meat','rice_2_fish','rice_2_meat_natto','rice_2_fish_natto','noodles','other']});
function hasHealthField_(object,key){return Object.prototype.hasOwnProperty.call(object||{},key);}
function validateContentField_(payload,typeKey,otherKey,options,required){if(!hasHealthField_(payload,typeKey)){if(required)throw healthErr_('INVALID_INPUT');return;}const type=String(payload[typeKey]||'');if(options.indexOf(type)<0)throw healthErr_('INVALID_INPUT');const other=hasHealthField_(payload,otherKey)?String(payload[otherKey]||'').trim():'';if(other.length>100)throw healthErr_('INVALID_INPUT');if(type==='other'&&!other)throw healthErr_('INVALID_INPUT');}
function validateSlotContent_(slot,payload){if(slot==='morning'){validateContentField_(payload,'morningMealType','morningMealOther',HEALTH_CONTENT_OPTIONS.morningMealType,payload.morningStaple!=='none');validateContentField_(payload,'morningWaterType','morningWaterOther',HEALTH_CONTENT_OPTIONS.morningWaterType,payload.morningWater);validateContentField_(payload,'morningConditionType','morningConditionOther',HEALTH_CONTENT_OPTIONS.conditionType,payload.morningCondition);return;}if(slot==='lunch'){validateContentField_(payload,'lunchMealType','lunchMealOther',HEALTH_CONTENT_OPTIONS.lunchMealType,payload.lunchAmount!=='none');validateContentField_(payload,'lunchWaterType','lunchWaterOther',HEALTH_CONTENT_OPTIONS.lunchWaterType,payload.lunchWater);validateContentField_(payload,'lunchConditionType','lunchConditionOther',HEALTH_CONTENT_OPTIONS.conditionType,payload.lunchCondition);return;}if(slot==='post_training'){validateContentField_(payload,'postTrainingSnackType','postTrainingSnackOther',HEALTH_CONTENT_OPTIONS.postTrainingSnackType,Number(payload.postTrainingOnigiriCount)>0);validateContentField_(payload,'postTrainingWaterType','postTrainingWaterOther',HEALTH_CONTENT_OPTIONS.lunchWaterType,payload.postTrainingWater);validateContentField_(payload,'postTrainingProteinAmount','postTrainingProteinOther',HEALTH_CONTENT_OPTIONS.postTrainingProteinAmount,payload.postTrainingProteinSource!=='none');validateContentField_(payload,'postTrainingConditionType','postTrainingConditionOther',HEALTH_CONTENT_OPTIONS.conditionType,payload.postTrainingCondition);return;}if(slot==='dinner')validateContentField_(payload,'dinnerMealType','dinnerMealOther',HEALTH_CONTENT_OPTIONS.dinnerMealType,Number(payload.dinnerRiceBowls)>0);}
function validateDaily_(b) { if(!healthUuid_(b.clientRequestId)||!SLOT[b.slot]||(b.isCorrection!==undefined&&typeof b.isCorrection!=='boolean')) throw healthErr_('INVALID_INPUT'); validateDate_(b.localDate); const p=b.payload||{}; const oneOf=function(value,list){return list.indexOf(value)>=0;}; if(b.slot==='morning'&&(!oneOf(p.morningStaple,['none','small','normal'])||!oneOf(p.morningProteinSource,['none','egg','natto','dairy','tofu','fish','protein','other'])||!validateOptionalHealthBoolean_(p,'morningWater')||!validateOptionalHealthBoolean_(p,'morningMedication')||!validateOptionalHealthBoolean_(p,'morningCondition')))throw healthErr_('INVALID_INPUT'); if(b.slot==='lunch'&&(!oneOf(p.lunchAmount,['none','half','most','all'])||!oneOf(p.lunchProteinSource,['none','included','unknown'])||!validateOptionalHealthBoolean_(p,'lunchWater')||!validateOptionalHealthBoolean_(p,'lunchCondition')))throw healthErr_('INVALID_INPUT'); if(b.slot==='post_training'&&(!oneOf(p.postTrainingStatus,['recorded','rest_day'])||!Number.isInteger(Number(p.postTrainingOnigiriCount))||Number(p.postTrainingOnigiriCount)<0||Number(p.postTrainingOnigiriCount)>10||!oneOf(p.postTrainingProteinSource,['none','protein','milk','yogurt','soy','other'])||!validateOptionalHealthBoolean_(p,'postTrainingWater')||!validateOptionalHealthBoolean_(p,'postTrainingCondition')))throw healthErr_('INVALID_INPUT'); if(b.slot==='dinner'&&(!Number.isInteger(Number(p.dinnerRiceBowls))||Number(p.dinnerRiceBowls)<0||Number(p.dinnerRiceBowls)>10||!Number.isInteger(Number(p.dinnerNattoPacks))||Number(p.dinnerNattoPacks)<0||Number(p.dinnerNattoPacks)>10||!oneOf(p.dinnerExtraProteinSource,['none','egg','dairy','tofu','fish','protein','other'])||!validateOptionalHealthBoolean_(p,'dinnerMedication')||!validateOptionalHealthBoolean_(p,'bedtime')))throw healthErr_('INVALID_INPUT'); if(b.slot==='condition'&&(!oneOf(p.conditionAppetite,['good','normal','low'])||!Array.isArray(p.symptoms)||p.symptoms.some(function(x){return ['dizziness','headache','nausea','cramps','marked_fatigue'].indexOf(x)<0;})||String(p.note||'').length>200))throw healthErr_('INVALID_INPUT'); validateSlotContent_(b.slot,p); }
function validateWeight_(b) { if(!healthUuid_(b.clientRequestId)||!Number.isFinite(Number(b.weightKg))||Number(b.weightKg)<20||Number(b.weightKg)>200)throw healthErr_('INVALID_INPUT');validateDate_(b.measuredDate); }
function safeJsonArray_(value){try{const out=JSON.parse(value||'[]');return Array.isArray(out)?out:[];}catch(_){return [];}}
function healthDate_(value){if(Object.prototype.toString.call(value)==='[object Date]'&&!isNaN(value))return Utilities.formatDate(value,'Asia/Tokyo','yyyy-MM-dd');const s=String(value||'');return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:'';}
